name: CI
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # HACK to enable/disable the max CI based on presence/absence of secret. See also:
  # https://github.com/actions/runner/issues/1138
  max-secrets:
    runs-on: ubuntu-latest
    name: Check for Max SDK
    outputs:
      HAS_MACHINE_USER_TOKEN: ${{ steps.check.outputs.MACHINE_USER_TOKEN }}
    steps:
      - name: Check for Secret
        id: check
        run: echo "MACHINE_USER_TOKEN=${{ env.MACHINE_USER_TOKEN != ''}}" >> $GITHUB_OUTPUT
        env:
          MACHINE_USER_TOKEN: ${{ secrets.MACHINE_USER_REPO_READ }}

  windows:
    runs-on: windows-2019
    name: ${{ matrix.platform.str }}-${{ matrix.cfg.str }}
    needs: ["max-secrets"]
    strategy:
      matrix:
        platform:
          - { generator: Visual Studio 16 2019, max-version: 7, arch: Win32, qt-arch: win32_msvc2019, qt-version: 5.15.2,  str: windows-x86 }
          - { generator: Visual Studio 16 2019, max-version: 2022, arch: x64, qt-arch: win64_msvc2019_64, qt-version: 5.15.2,  str: windows-x64 }
        cfg:
          - { external: OFF, type: RelWithPDB, str: internal-release }
          - { external: OFF, type: Debug, str: internal-debug }
          - { external: ON, type: RelWithPDB, str: external-release }

    steps:
      - name: Checkout Plasma
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout MaxSDK
        continue-on-error: true
        if: needs.max-secrets.outputs.HAS_MACHINE_USER_TOKEN == 'true'
        uses: actions/checkout@v3
        with:
          repository: H-uruMachineUser/3dsMaxSDK
          token: ${{ secrets.MACHINE_USER_REPO_READ }}
          path: maxsdk

      - name: Install Qt
        continue-on-error: true
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.platform.qt-version }}
          arch: ${{ matrix.platform.qt-arch }}
          dir: ${{ github.workspace }}/qt

      - name: Setup NuGet
        run: |
          nuget sources add `
              -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" `
              -storepasswordincleartext `
              -name "GitHub" `
              -username "${{ github.repository_owner }}" `
              -password "${{ secrets.GITHUB_TOKEN }}"

          nuget setapikey `
              "${{ secrets.GITHUB_TOKEN }}" `
              -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Configure
        run: |
          cmake `
            -G "${{ matrix.platform.generator }}" -A "${{ matrix.platform.arch }}" `
            -DPLASMA_BUILD_MAX_PLUGIN=ON `
            -DPLASMA_BUILD_TESTS=ON `
            -DPLASMA_BUILD_TOOLS=ON `
            -DPLASMA_EXTERNAL_RELEASE=${{ matrix.cfg.external }} `
            -D3dsm_PATH="${{ github.workspace }}/maxsdk/${{ matrix.platform.max-version }}" `
            -DVCPKG_INSTALL_OPTIONS=--clean-after-build `
            -S . -B build
        env:
          VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"

      - name: Build
        run: |
          cmake --build build --config "${{ matrix.cfg.type }}" -j 2

      - name: Install
        run: |
          cmake --build build --target INSTALL --config "${{ matrix.cfg.type }}" -j 2

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: plasma-${{ matrix.platform.str }}-${{ matrix.cfg.str }}
          path: build/install

      - name: Test
        run: |
          cmake --build build --target check --config "${{ matrix.cfg.type }}" -j 2

  max:
    # Can only run if we have a token for our super seekrit Max SDK repo. Sad.
    needs: ["max-secrets"]
    if: github.event_name == 'push' && needs.max-secrets.outputs.HAS_MACHINE_USER_TOKEN == 'true'

    runs-on: windows-2019
    name: maxplugin-${{ matrix.cfg.str }}
    strategy:
      matrix:
        cfg:
          # Max 7 and 2022 are tested in the x86 and x64 windows build jobs, respectively.
          - { sdk-version: 2008, generator: Visual Studio 16 2019, arch: Win32, str: 2008-windows-x86 }
          - { sdk-version: 2012, generator: Visual Studio 16 2019, arch: Win32, str: 2012-windows-x86 }
          - { sdk-version: 2013, generator: Visual Studio 16 2019, arch: x64, str: 2013-windows-x64 }
          - { sdk-version: 2017, generator: Visual Studio 16 2019, arch: x64, str: 2017-windows-x64 }
          - { sdk-version: 2019, generator: Visual Studio 16 2019, arch: x64, str: 2019-windows-x64 }
          - { sdk-version: 2020, generator: Visual Studio 16 2019, arch: x64, str: 2020-windows-x64 }

    steps:
      - name: Checkout Plasma
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout MaxSDK
        uses: actions/checkout@v3
        with:
          repository: H-uruMachineUser/3dsMaxSDK
          token: ${{ secrets.MACHINE_USER_REPO_READ }}
          path: maxsdk

      - name: Setup NuGet
        run: |
          nuget sources add `
              -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" `
              -storepasswordincleartext `
              -name "GitHub" `
              -username "${{ github.repository_owner }}" `
              -password "${{ secrets.GITHUB_TOKEN }}"

          nuget setapikey `
              "${{ secrets.GITHUB_TOKEN }}" `
              -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Configure
        run: |
          cmake `
            -G "${{ matrix.cfg.generator }}" -A "${{ matrix.cfg.arch }}" `
            -DPLASMA_BUILD_CLIENT=OFF `
            -DPLASMA_BUILD_MAX_PLUGIN=REQUIRED `
            -DPLASMA_BUILD_LAUNCHER=OFF `
            -DPLASMA_BUILD_TESTS=OFF `
            -DPLASMA_BUILD_TOOLS=OFF `
            -D3dsm_PATH="${{ github.workspace }}/maxsdk/${{ matrix.cfg.sdk-version }}" `
            -DVCPKG_INSTALL_OPTIONS=--clean-after-build `
            -S . -B build
        env:
          VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"

      - name: Build
        run: |
          cmake --build build --target INSTALL --config Release -j 2

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: max-${{ matrix.cfg.str }}
          path: build/install

  linux:
    runs-on: ubuntu-latest
    name: ${{ matrix.platform.str }}-${{ matrix.cfg.str }}
    strategy:
      matrix:
        platform:
          - { str: linux-x86, arch: x86, flags: "-m32" }
          - { str: linux-x64, arch: x64, flags: "-m64" }
        cfg:
          - { external: OFF, type: RelWithDebInfo, str: internal-release }
          - { external: OFF, type: Debug, str: internal-debug }
          - { external: ON, type: RelWithDebInfo, str: external-release }

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              autoconf \
              cmake \
              libcairo2 \
              libsecret-1-dev \
              libtool \
              nasm \
              ninja-build \
              qtbase5-dev

      - name: Install multilib dependencies
        if: matrix.platform.arch == 'x86'
        run: |
          sudo apt-get install -y gcc-multilib g++-multilib

          # We need to hack vcpkg to set the right linker flags
          sed -i '13i\   string(APPEND VCPKG_LINKER_FLAGS " -m32")' vcpkg/scripts/toolchains/linux.cmake

      - name: Setup NuGet
        run: |
          nuget sources add \
              -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
              -storepasswordincleartext \
              -name "GitHub" \
              -username "${{ github.repository_owner }}" \
              -password "${{ secrets.GITHUB_TOKEN }}"

          nuget setapikey \
              "${{ secrets.GITHUB_TOKEN }}" \
              -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Configure
        run: |
          cmake \
            -G Ninja \
            -DCMAKE_C_FLAGS=${{ matrix.platform.flags }} \
            -DCMAKE_CXX_FLAGS=${{ matrix.platform.flags }} \
            -DUSE_VCPKG=ON \
            -DVCPKG_TARGET_TRIPLET="${{ matrix.platform.arch }}-linux" \
            -DCMAKE_BUILD_TYPE=${{ matrix.cfg.type }} \
            -DPLASMA_BUILD_TESTS=ON \
            -DPLASMA_BUILD_TOOLS=ON \
            -DPLASMA_EXTERNAL_RELEASE=${{ matrix.cfg.external }} \
            -DVCPKG_INSTALL_OPTIONS=--clean-after-build \
            -S . -B build
        env:
          VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"

      - name: Build
        run: |
          cmake --build build -j 2

      - name: Test
        run: |
          cmake --build build --target check -j 2

      - name: Install
        run: |
          cmake --build build --target install -j 2


  macos:
    runs-on: macos-latest
    name: ${{ matrix.platform.str }}-${{ matrix.cfg.str }}
    strategy:
      matrix:
        platform:
          #- { str: macos-arm64, arch: arm64, triplet: arm64 }
          - { str: macos-x64, arch: x86_64, triplet: x64 }
        cfg:
          - { external: OFF, type: RelWithDebInfo, str: internal-release }
          - { external: OFF, type: Debug, str: internal-debug }
          - { external: ON, type: RelWithDebInfo, str: external-release }

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: |
          brew install \
              autoconf \
              automake \
              cairo \
              libtool \
              nasm \
              qt@5

      - name: Setup NuGet
        run: |
          nuget sources add \
              -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
              -storepasswordincleartext \
              -name "GitHub" \
              -username "${{ github.repository_owner }}" \
              -password "${{ secrets.GITHUB_TOKEN }}"

          nuget setapikey \
              "${{ secrets.GITHUB_TOKEN }}" \
              -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Configure
        run: |
          cmake \
            -G Xcode \
            -DUSE_VCPKG=ON \
            -DVCPKG_TARGET_TRIPLET="${{ matrix.platform.triplet}}-osx" \
            -DVCPKG_OSX_ARCHITECTURES=${{ matrix.platform.arch }} \
            -DVCPKG_OSX_DEPLOYMENT_TARGET=10.14 \
            -DCMAKE_OSX_ARCHITECTURES=${{ matrix.platform.arch }} \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 \
            -DCMAKE_FIND_FRAMEWORK=LAST \
            -DPLASMA_BUILD_TESTS=ON \
            -DPLASMA_BUILD_TOOLS=ON \
            -DPLASMA_EXTERNAL_RELEASE=${{ matrix.cfg.external }} \
            ${{ (matrix.platform.triplet == 'x64' && '-DQt5_ROOT=$(brew --prefix qt@5)') || '' }} \
            -DVCPKG_INSTALL_OPTIONS=--clean-after-build \
            -S . -B build
        env:
          VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"

      - name: Build
        run: |
          cmake --build build --config "${{ matrix.cfg.type }}" -j 2

      - name: Test
        run: |
          cmake --build build --target check --config "${{ matrix.cfg.type }}" -j 2

      - name: Install
        run: |
          cmake --build build --target install --config "${{ matrix.cfg.type }}" -j 2

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: plasma-${{ matrix.platform.str }}-${{ matrix.cfg.str }}
          path: build/install
